### ISSUE TITLE
A second Execute under one call ID records a response the child session cannot rebuild, so the record says the subagent read what it did not

### ISSUE THREAD

**Issue by ChristopherDavenport** [ChristopherDavenport/agentturn#87]
## Why this is necessary

When a `tools/agent` subagent is executed twice under one call ID, the second
run's response is recorded with no request hash. Everything downstream that
reads the child session then treats it as unverifiable: `Session.Verify`
returns `ErrNoHash` for it under `agentsession` v0.0.6, a CI gate on the
record reports a response nothing checked, and `agenteval`'s strict replay
refuses the whole child session up front.

The recorder is not at fault — it declines a hash it cannot stand behind,
which is the honest thing to do. The disagreement is upstream: the recorder
continues the child *session* at its leaf, accumulating both runs, while
`tools/agent` builds a **fresh agent** for each `Execute` whose request is
the new input alone. So the path rebuilds a context of every item under that
call, and the request carried one.

That divergence — between what the path says the subagent read and what the
subagent actually read — is the defect, and it is worth deciding rather than
tolerating, because a subagent that can be called twice is the normal case,
not an exotic one.

## Evidence

At `67d406f` (`main`):

- `tools/agent/agent.go:352` — `child := agentturn.New(a.cfg, opts...)`,
  inside `Execute` (`:327`). A new agent per call. Its transcript is whatever
  `a.opts.seed` supplies (`:334-338`) and otherwise empty; nothing reads the
  child session's recorded context.
- `session/session.go:726-742`, `Recorder.ChildContext` — the child session
  is named by `agentsession.SubsessionID(parentID, callID)`, so a second
  `Execute` under the same call ID reaches the same session and is appended
  at its leaf. The session accumulates both runs; the two agents do not.
- `session/records_test.go:574-577` states the recorder's intent, and it is
  the intent the tool does not implement: "A second run under the same call
  continues the child session at its leaf rather than minting a second
  session or starting a new root: **a subagent that is messaged again answers
  from its own context**, so its run belongs after the one before it." It
  does not answer from its own context. `Execute` gives it an empty one.
- `session/records_test.go:579` uses exactly this shape — the call
  `call_again` executed twice — and `:584` opens
  `agentsession.SubsessionID(s.ID(), "call_again")`. The record is:

  ```
  run config item:user item:assistant* response run   run item:user item:assistant* response run
  ```

  The first response hashes; the second does not.
- The assertion at `:594` is `verifyAll(t, again) != 2`, which counts
  responses. Under `agentsession` v0.0.5, which this module still requires
  (`session/go.mod:6`), `Verify` returns nil for an unhashed response, so
  nothing here sees it.

PR #85, which bumps that requirement to v0.0.6, makes it visible and **pins
it** rather than fixing it — `verifyAllUnhashed(t, again, 1)` with
`hashed(again) != 1`, and a comment stating the open question. So the gap
is not new, is not introduced by #85, and is currently recorded only in that
test's comment.

## Failure scenario

A product exposes a research subagent as a tool and the model calls it twice
in one turn with the same call ID — a retry after a thin answer, or a
`Sequential` batch that re-invokes.

The team gates CI on the record: open each session, walk the response
entries, fail if any `Verify` returns non-nil. After the `agentsession`
v0.0.6 bump this build goes red on a run that did nothing wrong, naming a
response in a child session with `no request hash recorded`. There is no
corresponding defect to fix — the run was correct, the record is honest, and
the only way to make the gate green is to special-case child sessions, which
is the gate being weakened to accommodate a modelling gap.

Second consequence, quieter: `agenteval` cannot replay such a run at all.
`replayable` refuses a session where any response carries no hash, so a suite
whose agent uses a repeatable subagent tool is unreplayable in strict mode
for a reason that has nothing to do with the configuration under test.

## Suggested fix

This needs a decision before a patch, and the decision is the deliverable.
Two coherent answers:

- **Seed the second execution from the child's recorded context.**
  `tools/agent`'s `Execute` reads the child session's leaf and passes it as
  the transcript, so the request is what the path rebuilds and the hash
  returns. This makes a second call a continuation, which matches what the
  session already says happened, and it changes what the subagent sees —
  today it starts clean, and this would give it the first execution's
  history. That is a product-visible behaviour change and arguably the right
  one, since two calls under one ID are one logical invocation.
- **Open a new root for the second execution.** The child session gains a
  second root rather than a second run on the same path, so each execution's
  path rebuilds exactly what that execution sent and both hash. This keeps
  today's "fresh agent per call" semantics and makes the record describe
  them. `ContextWithRetry` already does something adjacent for a call that
  means a clean start (`session/records_test.go:601-612`), which is evidence
  that the machinery is close to hand.

The first is a smaller change to the record and a larger one to behaviour;
the second is the reverse. Either closes the hash gap. Doing nothing is also
a position, but then the comment in the test should be the CHANGELOG's
problem too: a host gating on the record needs to be told that a repeated
subagent call legitimately produces an unhashed response.

Not in PR #85, which is about the pin. #85 pins the gap so a change to it is
seen; this is the change.

---
From a review of `compact.WithPin` and the request hash, 2026-09-21. Draft:
`pin-review/issues/09-agentturn-second-execute-under-one-call-id.md`; the
working is in `pin-review/AGENTTURN-PIN.md` §4.1 and §6.3.
